In [2]:
import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

In [3]:
df=pd.read_csv("train.csv")

In [4]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,Grade
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,5
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,8
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,9

# Encode all the category columns

In [5]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'Grade'],
      dtype='object')

In [6]:
ordinal_cat =["famsize",'Medu','Fedu',"traveltime","health","famrel","freetime","goout","Dalc","Walc","health"]
nominal_cat =["school","sex","address","Pstatus","Mjob",'Fjob',"reason","guardian","failures","schoolsup","famsup","paid","activities","nursery","higher","internet","romantic"]
numerical =["age","absences"]

In [7]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
le.fit_transform(df["famsize"])

array([0, 0, 1, ..., 0, 1, 1])

In [8]:
df_1=df.copy()

In [9]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
for i in ordinal_cat:
    df_1[i]=le.fit_transform(df[i])
df_1

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,Grade
0,GP,F,18,U,0,A,4,4,at_home,teacher,...,no,no,3,2,3,0,0,2,6,6
1,GP,F,17,U,0,T,1,1,at_home,other,...,yes,no,4,2,2,0,0,2,4,5
2,GP,F,15,U,1,T,1,1,at_home,other,...,yes,no,3,2,1,1,2,2,10,8
3,GP,F,15,U,0,T,4,2,health,services,...,yes,yes,2,1,1,0,0,4,2,15
4,GP,F,16,U,0,T,3,3,other,other,...,no,no,3,2,1,0,1,4,4,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,MS,F,19,R,0,T,2,3,services,other,...,yes,no,4,3,1,0,1,4,4,10
1040,MS,F,18,U,1,T,3,1,teacher,services,...,yes,no,3,2,3,0,0,0,4,15
1041,MS,F,18,U,0,T,1,1,other,other,...,no,no,0,0,0,0,0,4,6,11
1042,MS,M,17,U,1,T,3,1,services,services,...,yes,no,1,3,4,2,3,1,6,10
1043,MS,M,18,R,1,T,3,2,services,other,...,yes,no,3,3,0,2,3,4,4,11

In [10]:
df_1=pd.get_dummies(df_1,columns=nominal_cat,drop_first=True)

In [11]:
# split the data into features and target
x=df_1.copy()
y=x.pop("Grade")

In [12]:
x_train,x_val,y_train,y_val=train_test_split(x,y,random_state=42,test_size=0.2)

# First Algorithm

In [13]:
lr=LinearRegression()
model_1=lr.fit(x_train,y_train)

predict_1= model_1.predict(x_val)
eval_1= mean_absolute_error(y_val,predict_1)
print(f"the mean absolute error by {lr} is {eval_1}")

the mean absolute error by LinearRegression() is 2.2669340107690217

In [14]:
ls=Lasso()
model_2=ls.fit(x_train,y_train)

predict_2= model_2.predict(x_val)
eval_2= mean_absolute_error(y_val,predict_2)
print(f"the mean absolute error by {ls} is {eval_2}")

the mean absolute error by Lasso() is 2.616935547984805

In [15]:
dr=DecisionTreeRegressor()
model_3=dr.fit(x_train,y_train)

predict_3= model_3.predict(x_val)
eval_3= mean_absolute_error(y_val,predict_3)
print(f"the mean absolute error by {dr} is {eval_3}")

the mean absolute error by DecisionTreeRegressor() is 2.8062200956937797

In [16]:
sv=SVR()
model_4=sv.fit(x_train,y_train)

predict_4= model_4.predict(x_val)
eval_4= mean_absolute_error(y_val,predict_4)
print(f"the mean absolute error by {sv} is {eval_4}")

the mean absolute error by SVR() is 2.445943468018135

In [17]:
ab=AdaBoostRegressor()
model_5=ab.fit(x_train,y_train)

predict_5= model_5.predict(x_val)
eval_5= mean_absolute_error(y_val,predict_5)
print(f"the mean absolute error by {ab} is {eval_5}")

the mean absolute error by AdaBoostRegressor() is 2.3356192829416824

In [18]:
gb=GradientBoostingRegressor()
model_6=gb.fit(x_train,y_train)

predict_6= model_6.predict(x_val)
eval_6= mean_absolute_error(y_val,predict_6)
print(f"the mean absolute error by {gb} is {eval_6}")

the mean absolute error by GradientBoostingRegressor() is 2.2146248727950364

# Focusing on the best algorithm and try to make even more better

In [19]:
# features selection
# features Engineering
# hyperparameter tuning

 -1 to 1

In [24]:
c

age                 -0.127104
famsize              0.066003
Medu                 0.225589
Fedu                 0.184697
traveltime          -0.119439
studytime            0.189784
famrel               0.045621
freetime            -0.062740
goout               -0.107234
Dalc                -0.139786
Walc                -0.131306
health              -0.080805
absences            -0.079030
Grade                1.000000
school_MS           -0.144222
sex_M               -0.023510
address_U            0.121760
Pstatus_T           -0.016779
Mjob_health          0.110578
Mjob_other          -0.073843
Mjob_services        0.047987
Mjob_teacher         0.099392
Fjob_health          0.044542
Fjob_other          -0.046451
Fjob_services       -0.021728
Fjob_teacher         0.127381
reason_home          0.009645
reason_other        -0.043245
reason_reputation    0.138320
guardian_mother     -0.000492
guardian_other      -0.092053
failures_1          -0.270895
failures_2          -0.182381
failures_3          -0.210881
schoolsup_yes       -0.106611
famsup_yes          -0.000963
paid_yes            -0.042102
activities_yes       0.052199
nursery_yes          0.048910
higher_yes           0.261485
internet_yes         0.114029
romantic_yes        -0.090832
Name: Grade, dtype: float64

In [25]:
c=df_1.corr()["Grade"]

In [28]:
import statsmodels.api as sm

model = sm.OLS(y, x).fit()

In [29]:
0.05

0.05

In [30]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  Grade   R-squared (uncentered):                   0.944
Model:                            OLS   Adj. R-squared (uncentered):              0.942
Method:                 Least Squares   F-statistic:                              416.1
Date:                Sat, 22 Jun 2024   Prob (F-statistic):                        0.00
Time:                        15:12:09   Log-Likelihood:                         -2541.8
No. Observations:                1044   AIC:                                      5166.
Df Residuals:                    1003   BIC:                                      5369.
Df Model:                          41
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
age                   0.4528      0.043     10.455      0.000       0.368       0.538
famsize               0.4545      0.203      2.237      0.026       0.056       0.853
Medu                  0.1829      0.129      1.421      0.156      -0.070       0.435
Fedu                  0.1127      0.114      0.987      0.324      -0.111       0.337
traveltime            0.0071      0.134      0.053      0.957      -0.256       0.270
studytime             0.4554      0.117      3.891      0.000       0.226       0.685
famrel                0.1208      0.099      1.225      0.221      -0.073       0.314
freetime              0.1191      0.094      1.274      0.203      -0.064       0.303
goout                -0.2646      0.090     -2.927      0.003      -0.442      -0.087
Dalc                 -0.1422      0.130     -1.092      0.275      -0.398       0.113
Walc                 -0.0109      0.100     -0.109      0.913      -0.208       0.186
health               -0.1145      0.065     -1.762      0.078      -0.242       0.013
absences             -0.0116      0.015     -0.756      0.450      -0.042       0.019
school_MS            -0.3119      0.241     -1.297      0.195      -0.784       0.160
sex_M                 0.0601      0.206      0.292      0.770      -0.344       0.464
address_U             0.3982      0.223      1.786      0.074      -0.039       0.836
Pstatus_T             0.2624      0.291      0.903      0.367      -0.308       0.833
Mjob_health           0.9801      0.451      2.175      0.030       0.096       1.864
Mjob_other            0.0831      0.266      0.312      0.755      -0.440       0.606
Mjob_services         0.5318      0.316      1.683      0.093      -0.088       1.152
Mjob_teacher         -0.1523      0.418     -0.365      0.715      -0.972       0.667
Fjob_health           0.5311      0.603      0.881      0.378      -0.651       1.714
Fjob_other            0.3238      0.384      0.844      0.399      -0.429       1.077
Fjob_services         0.2073      0.402      0.516      0.606      -0.581       0.995
Fjob_teacher          1.5190      0.542      2.801      0.005       0.455       2.583
reason_home           0.1583      0.234      0.678      0.498      -0.300       0.617
reason_other          0.1454      0.317      0.459      0.646      -0.476       0.767
reason_reputation     0.3226      0.244      1.323      0.186      -0.156       0.801
guardian_mother      -0.1450      0.223     -0.651      0.515      -0.582       0.292
guardian_other       -0.0265      0.426     -0.062      0.950      -0.862       0.809
failures_1           -2.4596      0.301     -8.180      0.000      -3.050      -1.870
failures_2           -3.3370      0.530     -6.300      0.000      -4.376      -2.298
failures_3           -3.4954      0.557     -6.274      0.000      -4.589      -2.402
schoolsup_yes        -1.1046      0.287     -3.845      0.000      -1.668      -0.541
famsup_yes           -0.1277      0.190     -0.673      0.501      -0.500       0.244
paid_yes             -0.8547      0.226     -3.789      0.000      -1.297      -0.412
activities_yes        0.1329      0.184      0.721      0.471      -0.229       0.495
nursery_yes           0.1221      0.226      0.541      0.589      -0.321       0.565
higher_yes            1.9291      0.336      5.745      0.000       1.270       2.588
internet_yes          0.4092      0.238      1.722      0.085      -0.057       0.876
romantic_yes         -0.4886      0.192     -2.540      0.011      -0.866      -0.111
==============================================================================
Omnibus:                       63.531   Durbin-Watson:                   1.938
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               85.024
Skew:                          -0.534   Prob(JB):                     3.45e-19
Kurtosis:                       3.901   Cond. No.                         179.
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [31]:
import statsmodels.api as sm

model = sm.OLS(y, x).fit()

In [32]:
model.pvalues.max()

0.9574664262661455

In [38]:
# To return the max pvalues

model.pvalues.idxmax()

'traveltime'

In [41]:
def back_elimination(y,x,significant_level=0.05):
    while True:
        model = sm.OLS(y,x).fit()
        all_pvalues = model.pvalues
        max_pvalue = all_pvalues.max()
        if max_pvalue > significant_level:
            col_to_remove = all_pvalues.idxmax()
            x = x.drop(columns=[col_to_remove])
        else:
            break
    return model

In [42]:
signal_features=back_elimination(y,x)

In [43]:
signal_features.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  Grade   R-squared (uncentered):                   0.943
Model:                            OLS   Adj. R-squared (uncentered):              0.942
Method:                 Least Squares   F-statistic:                              1005.
Date:                Sat, 22 Jun 2024   Prob (F-statistic):                        0.00
Time:                        15:35:26   Log-Likelihood:                         -2552.9
No. Observations:                1044   AIC:                                      5140.
Df Residuals:                    1027   BIC:                                      5224.
Df Model:                          17
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
age               0.4809      0.026     18.188      0.000       0.429       0.533
famsize           0.3903      0.193      2.020      0.044       0.011       0.769
Medu              0.2432      0.090      2.701      0.007       0.066       0.420
studytime         0.5224      0.109      4.799      0.000       0.309       0.736
goout            -0.2463      0.077     -3.199      0.001      -0.397      -0.095
address_U         0.4778      0.202      2.362      0.018       0.081       0.875
Mjob_health       1.0873      0.347      3.131      0.002       0.406       1.769
Mjob_services     0.4913      0.217      2.269      0.023       0.066       0.916
Fjob_teacher      1.2878      0.381      3.380      0.001       0.540       2.035
failures_1       -2.5742      0.291     -8.855      0.000      -3.145      -2.004
failures_2       -3.4869      0.510     -6.831      0.000      -4.488      -2.485
failures_3       -3.5567      0.547     -6.503      0.000      -4.630      -2.483
schoolsup_yes    -1.0063      0.279     -3.608      0.000      -1.554      -0.459
paid_yes         -0.8801      0.219     -4.013      0.000      -1.310      -0.450
higher_yes        2.0760      0.323      6.421      0.000       1.442       2.710
internet_yes      0.5415      0.228      2.380      0.017       0.095       0.988
romantic_yes     -0.5649      0.187     -3.025      0.003      -0.931      -0.198
==============================================================================
Omnibus:                       56.586   Durbin-Watson:                   1.906
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               71.489
Skew:                          -0.514   Prob(JB):                     3.00e-16
Kurtosis:                       3.767   Cond. No.                         113.
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [44]:
col=signal_features.pvalues.index

In [45]:
new_col=x[col]

In [46]:
x_train,x_val,y_train,y_val=train_test_split(x,y,random_state=42,test_size=0.2)

In [47]:
gb=GradientBoostingRegressor() # creating instance of algorithm
model_6=gb.fit(x_train,y_train)

predict_6= model_6.predict(x_val)
eval_6= mean_absolute_error(y_val,predict_6)
print(f"the mean absolute error by {gb} is {eval_6}")

the mean absolute error by GradientBoostingRegressor() is 2.203770370627458

In [54]:
from sklearn.model_selection import RandomizedSearchCV

grim ={ "n_estimators":[100, 1000], "loss" :['squared_error','absolute_error'], "min_samples_leaf" :[1,2]}
model_rand = RandomizedSearchCV(estimator=gb,param_distributions=grim, cv=5, n_jobs=-1)

model_rand.fit(x_train, y_train)

best_model = model_rand.best_estimator_

model_6=best_model.fit(x_train,y_train)

predict_6= model_6.predict(x_val)
eval_6= mean_absolute_error(y_val,predict_6)
print(f"the mean absolute error by {gb} is {eval_6}")

C:\Users\Toru\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:292: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

the mean absolute error by GradientBoostingRegressor() is 2.2107038883295425